  export const International_regulations = [
    { title: "2017 TCFD Annex - ( Inactive )", url: "https://assets.bbhub.io/company/sites/60/2021/07/2021-TCFD-Implementing_Guidance.pdf" },
    { title: "2021 TCFD Annex - ( Inactive )", url: "https://www.fsb-tcfd.org/publications/" },
    { title: "AA1000AP - ( Active )", url: "https://www.accountability.org/standards/aa1000-accountability-principles" },
    { title: "AA1000AS v3. - ( Active )", url: "https://www.accountability.org/standards/aa1000-assurance-standard" },
    { title: "AA1000SES - ( Active )", url: "https://www.accountability.org/standards/aa1000-stakeholder-engagement" },
    { title: "Cartagena Protocol - ( Active )", url: "https://bch.cbd.int/protocol/background" },
    { title: "CBAM - ( Active )", url: "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32023R0956" },
    { title: "Climate Delegated Act - ( Active )", url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32022R1214" },
    { title: "CSDDD - ( Active )", url: "https://commission.europa.eu/topics/business-and-industry/doing-business-eu/sustainability-due-diligence-responsible-business/corporate-sustainability-due-diligence_en" },
    { title: "CSRD - ( Active )", url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=CELEX:32022L2464" },
    { title: "Environmental Delegated Act - ( Active )", url: "https://finance.ec.europa.eu/regulation-and-supervision/financial-services-legislation/implementing-and-delegated-acts/taxonomy-regulation_en" },
    { title: "Equator Principles - ( Active )", url: "https://equator-principles.com/" },
    { title: "ESRD - ( Active )", url: "https://eur-lex.europa.eu/legal-content/EN/TXT/PDF/?uri=CELEX:32023R2772" },
    { title: "EU Taxonomy - ( Active )", url: "https://finance.ec.europa.eu/sustainable-finance/tools-and-standards/eu-taxonomy-sustainable-activities_en" },
    { title: "European Green Deal - ( Active )", url: "https://eur-lex.europa.eu/legal-content/EN/TXT/?uri=celex:52019DC0640" },
    { title: "Frequently asked questions on climate-related financial risks (FAQs) - ( Active )", url: "https://www.bis.org/bcbs/publ/d543.pdf" },
    { title: "GBP 2014 - ( Inactive )", url: "https://www.icmagroup.org/assets/documents/Regulatory/Green-Bonds/Green-Bonds-Principles-2014.pdf" },
    { title: "GBP 2015 - ( Inactive )", url: "https://www.icmagroup.org/assets/documents/Regulatory/Green-Bonds/GBP_2015_27-March.pdf" },
    { title: "GBP 2016 - ( Inactive )", url: "https://www.icmagroup.org/assets/documents/Regulatory/Green-Bonds/GBP-2016-Final-16-June-2016.pdf" },
    { title: "GBP 2017 - ( Inactive )", url: "https://www.icmagroup.org/assets/documents/Regulatory/Green-Bonds/GreenBondsBrochure-JUNE2017.pdf" },
    { title: "GBP 2018 - ( Inactive )", url: "https://www.icmagroup.org/assets/green-bond-principles-june-2018-140618-v2.pdf" },
    { title: "GBP 2022 - ( Inactive )", url: "https://www.icmagroup.org/assets/documents/Sustainable-finance/2022-updates/Green-Bond-Principles-June-2022-060623.pdf" },
    { title: "GBP 2025 - ( Active )", url: "https://www.icmagroup.org/assets/documents/Sustainable-finance/2025-updates/Green-Bond-Principles-GBP-June-2025.pdf" },
    { title: "GHG Protocol - ( Active )", url: "https://ghgprotocol.org/sites/default/files/standards/ghg-protocol-revised.pdf" },
    { title: "GLP 2018 - ( Inactive )", url: "https://www.icmagroup.org/assets/documents/Regulatory/Green-Bonds/LMA_Green_Loan_Principles_Booklet-220318.pdf" },
    { title: "GLP 2021 - ( Inactive )", url: "https://greenfinanceportal.env.go.jp/pdf/Green_Loan_Principles_Feb2021_V04.pdf" },
    { title: "GLP 2025 - ( Active )", url: "https://www.lsta.org/content/green-loan-principles/" },
    { title: "GRI Guidelines G1 - ( Inactive )", url: "https://www.globalreporting.org/about-gri/vision-mission-and-history/" },
    { title: "GRI Guidelines G2 - ( Inactive )", url: "https://www.globalreporting.org/about-gri/vision-mission-and-history/" },
    { title: "GRI Guidelines G3 - ( Inactive )", url: "https://www.globalreporting.org/about-gri/vision-mission-and-history/" },
    { title: "GRI Guidelines G4 - ( Inactive )", url: "https://www.globalreporting.org/about-gri/vision-mission-and-history/" },
    { title: "GRI Standards - ( Inactive )", url: "https://www.globalreporting.org/about-gri/vision-mission-and-history/" },
    { title: "GRI Standards - ( Active )", url: "https://www.globalreporting.org/how-to-use-the-gri-standards/gri-standards-traditional-chinese-translations/" },
    { title: "Guide to Transition Loans - ( Active )", url: "https://www.lma.eu.com/application/files/8017/6121/0645/Guide_to_Transition_Loans_-_16_October_2025.pdf" },
    { title: "IFC Performance Standards on Environmental and Social Sustainability - ( Active )", url: "https://www.ifc.org/content/dam/ifc/doc/mgrt/ifc-performance-standards.pdf" },
    { title: "IFRS S1 & S2 - ( Active )", url: "https://www.ifrs.org/content/dam/ifrs/publications/pdf-standards-issb/english/2023/issued/part-a/issb-2023-a-ifrs-s1-general-requirements-for-disclosure-of-sustainability-related-financial-information.pdf?bypass=on" },
    { title: "IFRS S2 - ( Active )", url: "https://www.ifrs.org/content/dam/ifrs/publications/pdf-standards-issb/english/2023/issued/part-a/issb-2023-a-ifrs-s2-climate-related-disclosures.pdf?bypass=on" },
    { title: "International IR Framework - ( Active )", url: "https://www.ifrs.org/content/dam/ifrs/integrated-reporting/framework-and-translations/ir-framework-trad-chin-final.pdf" },
    { title: "IPCC - ( Active )", url: "https://www.ipcc.ch/" },
    { title: "ISAE 3000 (Revised) - ( Active )", url: "https://www.iaasb.org/publications/international-standard-assurance-engagements-isae-3000-revised-assurance-engagements-other-audits-or" },
    { title: "ISAE 3410(20261215廢止) - ( Inactive )", url: "https://www.fsr.dk/Files/Files/Dokumenter/Faglig/Revision/Revision og erkl%C3%A6ringsopgaver/ISAE 3410-Final 6-6-12.pdf?utm_source=chatgpt.com" },
    { title: "ISO 14064-1 - ( Active )", url: "https://cdn.standards.iteh.ai/samples/66453/376be09b95704a2b91271e1587a2f000/ISO-14064-1-2018.pdf" },
    { title: "ISSA 5000(20261215-取代ISAE3410) - ( Adopted )", url: "https://www.iaasb.org/publications/international-standard-sustainability-assurance-5000-general-requirements-sustainability-assurance" },
    { title: "Nagoya – Kuala Lumpur Supplementary Protocol - ( Active )", url: "https://bch.cbd.int/protocol/supplementary?_gl=1*dd9um1*_ga*ODI0NTkwMDc4LjE3NzA1NDc4NjA.*_ga_7S1TPRE7F5*czE3NzA2MTM0MjYkbzQkZzEkdDE3NzA2MTUwMzgkajYwJGwwJGgw" },
    { title: "Nagoya Protocol - ( Active )", url: "https://www.cbd.int/abs/about/default.shtml" },
    { title: "NFRD - ( Inactive )", url: "https://www.europarl.europa.eu/RegData/etudes/BRIE/2021/654213/EPRS_BRI(2021)654213_EN.pdf" },
    { title: "Paris Agreement - ( Active )", url: "https://unfccc.int/process-and-meetings/the-paris-agreement" },
    { title: "PRB - ( Active )", url: "https://www.unepfi.org/banking/bankingprinciples/" },
    { title: "PRI - ( Active )", url: "https://www.unpri.org/about-PRI" },
    { title: "Principles for the effective management and supervision of climate-related financial risks  - ( Active )", url: "https://www.bis.org/bcbs/publ/d532.pdf" },
    { title: "PSI - ( Active )", url: "https://www.unepfi.org/industries/insurance/the-principles-for-sustainable-insurance/" },
    { title: "SASB Standards - ( Active )", url: "https://sasb.ifrs.org/archive/standard-setting/" },
    { title: "SBG 2017 - ( Inactive )", url: "https://www.icmagroup.org/assets/documents/Regulatory/Green-Bonds/SustainabilityBondGuidelines-JUNE2017.pdf" },
    { title: "SBG 2018 - ( Inactive )", url: "https://www.icmagroup.org/assets/documents/Regulatory/Green-Bonds/June-2018/Sustainability-Bond-Guidelines---June-2018-140618-WEB.pdf" },
    { title: "SBG 2021 - ( Active )", url: "https://www.icmagroup.org/assets/documents/Sustainable-finance/2021-updates/Sustainability-Bond-Guidelines-June-2021-140621.pdf" },
    { title: "SBP 2017 - ( Inactive )", url: "https://www.icmagroup.org/assets/documents/Regulatory/Green-Bonds/SocialBondsBrochure-JUNE2017.pdf" },
    { title: "SBP 2018 - ( Inactive )", url: "https://www.icmagroup.org/assets/documents/Regulatory/Green-Bonds/June-2018/Social-Bond-Principles---June-2018-140618-WEB.pdf" },
    { title: "SBP 2020 - ( Inactive )", url: "https://www.icmagroup.org/assets/documents/Regulatory/Green-Bonds/June-2020/Social-Bond-PrinciplesJune-2020-090620.pdf" },
    { title: "SBP 2022 - ( Inactive )", url: "https://www.icmagroup.org/assets/documents/Sustainable-finance/2022-updates/Social-Bond-Principles_June-2022-280622.pdf" },
    { title: "SBP 2023 - ( Inactive )", url: "https://www.icmagroup.org/assets/documents/Sustainable-finance/2023-updates/Social-Bond-Principles-SBP-June-2023-220623.pdf" },
    { title: "SBP 2025 - ( Active )", url: "https://www.icmagroup.org/assets/documents/Sustainable-finance/2025-updates/Social-Bond-Principles-SBP-June-2025.pdf" },
    { title: "SDGs - ( Active )", url: "https://sdgs.un.org/goals" },
    { title: "SLBP 2020 - ( Inactive )", url: "https://www.icmagroup.org/assets/documents/Regulatory/Green-Bonds/June-2020/Sustainability-Linked-Bond-Principles-June-2020-171120.pdf" },
    { title: "SLBP 2023 - ( Inactive )", url: "https://www.icmagroup.org/assets/documents/Sustainable-finance/2023-updates/Sustainability-Linked-Bond-Principles-June-2023-220623.pdf" },
    { title: "SLBP 2024 - ( Active )", url: "https://www.icmagroup.org/assets/documents/Sustainable-finance/2024-updates/Sustainability-Linked-Bond-Principles-June-2024.pdf" },
    { title: "SLLP 2019 - ( Inactive )", url: "https://www.icmagroup.org/assets/documents/Regulatory/Green-Bonds/LMASustainabilityLinkedLoanPrinciples-270919.pdf" },
    { title: "SLLP 2020 - ( Active )", url: "https://www.lsta.org/content/sustainability-linked-loan-principles-sllp/" },
    { title: "SLP - ( Active )", url: "https://www.lsta.org/content/social-loan-principles-slp/" },
    { title: "Taxonomy Regulation (TR) - ( Active )", url: "https://eur-lex.europa.eu/eli/reg/2020/852/oj/eng" },
    { title: "TCFD Recommendation - ( Inactive )", url: "https://assets.bbhub.io/company/sites/60/2021/10/FINAL-2017-TCFD-Report.pdf" },
    { title: "UNCBD - ( Active )", url: "https://www.cbd.int/convention/text" },
    { title: "UNCCD - ( Active )", url: "https://www.unccd.int/convention/history-unccd" },
    { title: "UNFCCC - ( Active )", url: "https://unfccc.int/process-and-meetings/united-nations-framework-convention-on-climate-change" },
    { title: "Voluntary disclosure framework for climate-related financial risks - ( Adopted )", url: "https://www.bis.org/bcbs/publ/d597.pdf" },
  ];
  
  export const Taiwan_regulations = [
    { title: "上市公司編製與申報永續報告書作業辦法(2025.5.5修正) - ( Active )", url: "https://twse-regulation.twse.com.tw/m/LawContent.aspx?FID=FL075209" },
    { title: "上市櫃公司公司治理實務守則 - ( Active )", url: "https://twse-regulation.twse.com.tw/m/LawContent.aspx?FID=FL020553" },
    { title: "上市櫃公司永續發展行動方案 - ( Active )", url: "https://cgc.twse.com.tw/responsibilityPlan/listCh" },
    { title: "上市櫃公司永續發展行動方案2023 - ( Active )", url: "https://www.fsc.gov.tw/uploaddowndoc?file=news/202303290815110.pdf&filedisplay=%E4%B8%8A%E5%B8%82%E6%AB%83%E5%85%AC%E5%8F%B8%E6%B0%B8%E7%BA%8C%E7%99%BC%E5%B1%95%E8%A1%8C%E5%8B%95%E6%96%B9%E6%A1%88.pdf&flag=doc" },
    { title: "上市櫃公司永續發展實務守則(2025.9.2修正) - ( Active )", url: "https://twse-regulation.twse.com.tw/TW/law/DAT0201.aspx?FLCODE=FL052368" },
    { title: "上市櫃公司氣候相關資訊揭露參考指引 - ( Active )", url: "https://www.selaw.com.tw/Chinese/RegulatoryInformationResult/Article?sysNumber=LW10867058&releaseDate=2025-05-06&__RequestVerificationToken=CfDJ8DYN5SflATpChfmwqyrS53vafZrbraPJQFaONmomeL9eYMeum0jzNm5qmKQVHHVmIjqpJyWJpkrhv4LIuIs5wg2w_HYbpGE6bcBz9bGue0oJe_N4BNcisB-OFX9fcu5ZqLz29XgsSA8FlnBK09Ox9OA" },
    { title: "上市櫃公司誠信經營守則 - ( Active )", url: "https://twse-regulation.twse.com.tw/m/LawContent.aspx?FID=FL055768" },
    { title: "上市櫃公司誠信經營守則 - ( Active )", url: "https://twse-regulation.twse.com.tw/m/LawContent.aspx?FID=FL055768" },
    { title: "上市櫃公司薪資報酬委員會設置及行使職權辦法 - ( Active )", url: "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=G0400149" },
    { title: "公開發行公司建立內部控制制度處理準則 - ( Active )", url: "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=G0400045" },
    { title: "本國銀行氣候風險財務揭露指引 - ( Active )", url: "https://www.fsc.gov.tw/uploaddowndoc?file=news/202111301608270.pdf&filedisplay=%E9%99%84%E4%BB%B6+-+%E6%9C%AC%E5%9C%8B%E9%8A%80%E8%A1%8C%E6%B0%A3%E5%80%99%E9%A2%A8%E9%9A%AA%E8%B2%A1%E5%8B%99%E6%8F%AD%E9%9C%B2%E6%8C%87%E5%BC%95.pdf&flag=doc" },
    { title: "本國銀行氣候風險財務揭露指引 - ( Active )", url: "https://www.fsc.gov.tw/ch/home.jsp?id=96&parentpath=0,2&mcustomize=news_view.jsp&dataserno=202111300008&dtable=News" },
    { title: "永續公司治理藍圖1.0 - ( Inactive )", url: "https://www.fsc.gov.tw/fckdowndoc?file=/2013%E5%BC%B7%E5%8C%96%E6%88%91%E5%9C%8B%E5%85%AC%E5%8F%B8%E6%B2%BB%E7%90%86%E8%97%8D%E5%9C%96(1).pdf&flag=doc" },
    { title: "永續公司治理藍圖2.0 - ( Inactive )", url: "https://www.fsc.gov.tw/fckdowndoc?file=/%E6%96%B0%E7%89%88%E5%85%AC%E5%8F%B8%E6%B2%BB%E7%90%86%E8%97%8D%E5%9C%96(2018~2020)20180328(2).pdf&flag=doc" },
    { title: "永續公司治理3.0 - ( Active )", url: "https://www.fsc.gov.tw/fckdowndoc?file=/%E5%85%AC%E5%8F%B8%E6%B2%BB%E7%90%863_0-%E6%B0%B8%E7%BA%8C%E7%99%BC%E5%B1%95%E8%97%8D%E5%9C%96.pdf&flag=doc" },
    { title: "永續金融先行者聯盟 - ( Active )", url: "https://www.facebook.com/sustainablefinance.tw/" },
    { title: "永續發展債券作業要點 - ( Active )", url: "https://www.selaw.com.tw/Chinese/RegulatoryInformationResult/Article?isIntegratedSearch=True&sysNumber=LW11001272&searchString1=%E7%B6%A0%E8%89%B2" },
    { title: "永續經濟活動認定參考指引第一版 - ( Inactive )", url: "https://ws.moi.gov.tw/Download.ashx?u=LzAwMS9VcGxvYWQvNDAwL3JlbGZpbGUvOTAwOS8yNzcxNDAvODcyYmViZmYtNGJkOS00YzZlLTg1NGMtYTE2MWVkZDUyNzZkLnBkZg%3d%3d&n=6ZmE5Lu2MeawuOe6jOe2k%2ba%2fn%2ba0u%2bWLleiqjeWumuWPg%2biAg%2baMh%2bW8lS5wZGY%3d" },
    { title: "永續經濟活動認定參考指引第二版 - ( Active )", url: "https://www.fsc.gov.tw/userfiles/file/1_%E6%B0%B8%E7%BA%8C%E7%B6%93%E6%BF%9F%E6%B4%BB%E5%8B%95%E8%AA%8D%E5%AE%9A%E5%8F%83%E8%80%83%E6%8C%87%E5%BC%95%E7%AC%AC%E4%BA%8C%E7%89%88.pdf" },
    { title: "我國接軌IFRS永續揭露準則藍圖 - ( Active )", url: "https://www.fsc.gov.tw/uploaddowndoc?file=news/202308171508440.pdf&filedisplay=%E9%99%84%E4%BB%B61-%E6%88%91%E5%9C%8B%E6%8E%A5%E8%BB%8CIFRS%E6%B0%B8%E7%BA%8C%E6%8F%AD%E9%9C%B2%E6%BA%96%E5%89%87%E8%97%8D%E5%9C%96.pdf&flag=doc" },
    { title: "金融友善服務準則 - (  )", url: "https://www.ba.org.tw/accessibility/index" },
    { title: "金融服務業公平待客原則 - ( Active )", url: "https://law.fsc.gov.tw/LawContent.aspx?id=GL001766" },
    { title: "金融服務業公平待客原則評核制度 - ( Active )", url: "https://www.fsc.gov.tw/ch/home.jsp?id=953&parentpath=0,5,943" },
    { title: "金融消費者保護法 - ( Active )", url: "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=G0380226" },
    { title: "金融控股公司公司治理實務守則 - ( Active )", url: "https://www.ba.org.tw/PublicInformation/Detail/5215?enumtype=ImportantnormType&type=2bae0643-ec93-49c0-a30e-4da6cbdacbc7" },
    { title: "金融控股公司及銀行業內部控制及稽核制度實施辦法 - ( Active )", url: "https://law.fsc.gov.tw/LawContent.aspx?id=FL049894" },
    { title: "金融檢查重點說明（年度） - ( Active )", url: "https://www.fsc.gov.tw/ch/home.jsp?id=96&parentpath=0,2&mcustomize=news_view.jsp&dataserno=202512180001&dtable=News" },
    { title: "保險業內部控制及稽核制度實施辦法 - ( Active )", url: "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=G0390052" },
    { title: "保險業公司治理實務守則 - ( Active )", url: "https://law.lia-roc.org.tw/Law/Content?lsid=FL034013" },
    { title: "保險業金融檢查手冊 - ( Active )", url: "https://www.feb.gov.tw/ch/home.jsp?id=275&parentpath=0,4,256" },
    { title: "保險業風險管理實務守則 - ( Active )", url: "https://law.fsc.gov.tw/LawContent.aspx?id=GL001093" },
    { title: "氣候變遷因應法 - ( Active )", url: "https://oaout.moenv.gov.tw/law/LawContent.aspx?id=GL005511" },
    { title: "氣候變遷因應法施行細則 - ( Active )", url: "https://oaout.moenv.gov.tw/law/LawContent.aspx?id=GL005953" },
    { title: "國家氣候變遷調適行動計畫 - ( Active )", url: "https://www.cca.gov.tw/information-service/info/3824.html" },
    { title: "國際審計與確信準則第 3000 號（ISAE 3000） - ( Active )", url: "https://www.ardf.org.tw/html/opinion/au/3000.pdf" },
    { title: "溫室氣體自願減量專案管理辦法 - ( Active )", url: "https://oaout.moenv.gov.tw/law/LawContent.aspx?id=GL007885" },
    { title: "溫室氣體抵換專案管理辦法 - ( Active )", url: "https://oaout.moenv.gov.tw/law/LawContent.aspx?id=GL006015" },
    { title: "溫室氣體排放量增量抵換管理辦法 - ( Active )", url: "https://law.moj.gov.tw/LawClass/LawAll.aspx?PCODE=O0020136" },
    { title: "溫室氣體排放量盤查登錄及查驗管理辦法 - ( Active )", url: "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=O0020102" },
    { title: "溫室氣體排放量盤查登錄管理辦法(105.1.5發布/114.12.19修正) - ( Active )", url: "https://oaout.moenv.gov.tw/law/LawContent.aspx?id=GL005954&kw=%E4%BA%8B%E6%A5%AD+%E6%BA%AB%E5%AE%A4%E6%B0%A3%E9%AB%94&media=print&utm_source=chatgpt.com" },
    { title: "溫室氣體減量及管理法施行細則 - ( Inactive )", url: "https://law.moj.gov.tw/LawClass/LawAll.aspx?pcode=O0020103" },
    { title: "溫管法  - ( Repealed )", url: "https://service.cca.gov.tw/File/Get/cca/zh-tw/Yut4R0X3cGPeg5h?utm_source=chatgpt.com" },
    { title: "碳費收費辦法 - ( Active )", url: "https://oaout.moenv.gov.tw/laW/LawContent.aspx?id=GL007914" },
    { title: "碳費徵收對象溫室氣體減量指定目標 - ( Active )", url: "https://oaout.moenv.gov.tw/law/LawContent.aspx?id=GL007916" },
    { title: "綠色金融行動方案1.0 - ( Inactive )", url: "https://www.fsc.gov.tw/websitedowndoc?file=chfsc/202510171142420.pdf&filedisplay=%E7%B6%A0%E8%89%B2%E9%87%91%E8%9E%8D%E8%A1%8C%E5%8B%95%E6%96%B9%E6%A1%881.0.pdf" },
    { title: "綠色金融行動方案2.0 - ( Inactive )", url: "https://www.fsc.gov.tw/websitedowndoc?file=chfsc/202104191513590.pdf&filedisplay=%E7%B6%A0%E8%89%B2%E9%87%91%E8%9E%8D%E8%A1%8C%E5%8B%95%E6%96%B9%E6%A1%882.0.pdf" },
    { title: "綠色金融行動方案3.0 - ( Active )", url: "https://www.fsc.gov.tw/websitedowndoc?file=chfsc/202209281336330.pdf&filedisplay=%E7%B6%A0%E8%89%B2%E9%87%91%E8%9E%8D%E8%A1%8C%E5%8B%95%E6%96%B9%E6%A1%883.0.pdf" },
    { title: "綠色及轉型金融行動方案 - ( Active )", url: "https://www.fsc.gov.tw/websitedowndoc?file=chfsc/202411011142040.pdf&filedisplay=%E7%B6%A0%E8%89%B2%E5%8F%8A%E8%BD%89%E5%9E%8B%E9%87%91%E8%9E%8D%E8%A1%8C%E5%8B%95%E6%96%B9%E6%A1%88.pdf" },
    { title: "臺灣2050淨零排放路徑及策略 - ( Active )", url: "https://ncsd.ndc.gov.tw/Fore/nsdn/about0/2050Path?utm_source=chatgpt.com" },
    { title: "臺灣2050淨零排放路徑及策略總說明 - ( Active )", url: "https://ncsd.ndc.gov.tw/Fore/nsdn/about0/2050Path" },
    { title: "臺灣總體減碳行動計畫2025 - ( Active )", url: "https://ws.ndc.gov.tw/Download.ashx?u=LzAwMS9hZG1pbmlzdHJhdG9yLzEwL3JlbGZpbGUvMC8xNDc2Mi9kNWMxZTgwYS0zZDY3LTQ0OWItYTJlNS1hMGY5ZDgwYmMzMGIucGRm&n=MjAyNeW5tDHmnIgyM%2baXpeWFrOW4g%2b%2b8muiHuueBo%2be4vemrlOa4m%2beis%2bihjOWLleioiOeVqy5wZGY%3d&icon=.pdf" },
    { title: "銀行公司治理實務守則 - ( Active )", url: "https://www.ba.org.tw/PublicInformation/Detail/5214?enumtype=ImportantnormType&type=303d023c-2b81-4cd2-8967-3dceb305fea6" },
    { title: "銀行業TCFD揭露建議書 - ( Active )", url: "https://dsp.tpex.org.tw/storage/csr/%E9%8A%80%E8%A1%8C%E6%A5%ADTCFD%E6%8F%AD%E9%9C%B2%E7%AF%84%E4%BE%8B.pdf" },
    { title: "銀行業金融檢查手冊 - ( Active )", url: "https://www.feb.gov.tw/ch/home.jsp?id=279&parentpath=0,4" },
    { title: "銀行業建立風險導向內部稽核制度實務守則 - (  )", url: "https://www.rootlaw.com.tw/LawArticle.aspx?LawID=A040390071000900-1050708" },
  ];
